И снова не проходит проверку.
js-tasks-ru/jsbasic-20220519_ilya-kopturevskiy pull request #8
Opened 2022-06-17 13:23 UTC by iKopturevskiy

Таблица создается. По клику удаляется строка.

2022-06-17 13:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-19 15:53 UTC, SinimaWath requested changes

2022-06-19 15:53 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this.elem = createTable(rows);
Давай попробуем переписать на методы класса

2022-06-19 15:53 UTC, SinimaWath commented on 6-module/1-task/index.js
> +  myScript.before(div);
По условию задачи, не нужно в документ вставлять верстку.

Надо просто создать DOM-елемент и записать его в this.elem

2022-06-19 15:53 UTC, SinimaWath commented on 6-module/1-task/index.js
> +function createTable(rows) {
Функцию сложно читать, так как очень много createElement, append, querySelector.

Давай попробуем сделать так:
- Сформировать строку с версткой, примерно так:
```
template() {
  return `
    <thead>
        <tr>
            <th>Имя</th>
            <th>Возраст</th>
            <th>Зарплата</th>
            <th>Город</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
       ${this.rows.map().join()}
    </tbody>
  `
}
```
- Вставлять эту верстку в елемент: `table.innerHtml = this.template()`;
- И только потом вешать обработчики событий

2022-06-19 18:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-20 17:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-20 19:43 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-21 19:23 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-06-22 09:24 UTC, SinimaWath approved these changes

2022-06-22 09:24 UTC, merged